### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by dobrosketchkun** [saic-mdal/lama#1]
Hello! 
Could you please tell us when the code will be available? We are eager to try your wonderful work.
Quoting your paper:
> The code is available at https://github.com/saic-mdal/lama.

**Comment by windj007** [comment]
Hi!

Thank you for your interest!

We are preparing the code for the release, but it will take some time. We hope to make it within month or two.

**Comment by senya-ashukha** [comment]
Hopefully faster, but the most optimistic estimate is ~2 weeks)

**Comment by andriyrizhiy** [comment]
Maybe you have a demo code? I'm very interested to see how your approach works in real photos

**Comment by senya-ashukha** [comment]
Unfortunately, we cannot release any code at the moment. There are two factors involved i) heave refactoring and testing are in progress ii) we need to receive a range of formal approvals.

You can refer to the link https://bit.ly/3k0gaIK where we test a method on real photos not included in any dataset. Basically, all examples in the paper are real photos from the internet and some personal ones.

**Comment by roimulia2** [comment]
Wonderful work! Is there any chance only the pre-trained model can be released without the code? For testing purposes?

**Comment by senya-ashukha** [comment]
Hi @roimulia2! The models should get through the same approval process as should code. However, I'm very optimistic about code release in the next couple of days.
