### ISSUE TITLE
Question about L1 loss weight_know vs weight_missing

### ISSUE THREAD

**Issue by Marcelo5444** [saic-mdal/lama#101]
Hi! First of all thanks for sharing the code. I have a doubt about the loss L1.First of all this loss does not appear at the paper right? Second of all about the loss weight_know vs weight_missing: Why in most of the configs you set weight_missing to 0, As I understand this weights the part of the masked image in order to make the network match the gt with the predicted in the zone to inpainted. That is the zone where mask == 1. Why You set that to 0? Have you studied this param on the effect of convergence?

**Comment by windj007** [comment]
Could you please point, which config has nonzero l1 weight for missing areas?

**Comment by Marcelo5444** [comment]
What I meant is that in previous post you said that L1 loss was not used but looking at the configs. It is used in may. One example of this is lama-celeba-hq/lama_small_train_masks

**Comment by windj007** [comment]
weight_known is only applied to parts of images outside the mask and it does not affect actual inpainting quality - you can safely switch it off. weight_missing is the weight of l1 inside mask - and it is set to 0 in all our configs. This is why I tell that L1 is not used.

> Also, why You set the weight_know to 10, this is to force that the inpainted image as a similar aspect in out-of-mask zones?

Original motivation was like that, but later we figured out that this is not necessary. weight_known is there just for historical reasons - and it can be safely removed

**Comment by Marcelo5444** [comment]
Can you point me to configurations trained with CelebHQ that weight_known is set to 0. In all of them weight_known is set to 10 and affects the training.

**Comment by windj007** [comment]
I did not tell that we have weight_known=0 in any configs. The points is that the resulting quality does not depend on this parameter be in 0 or 10 or 100.

**Comment by windj007** [comment]
I'm closing the issue for now. If you have any other questions, feel free to reopen it or create a new one.
