### ISSUE TITLE
Doubt about optimizer_idx

### ISSUE THREAD

**Issue by Marcelo5444** [saic-mdal/lama#102]
Looking at the code I found the _do_step function that as I can tell via torch ligthining what it does is train at each iteration one time the generator and the other the discrimantor? Is this always the receipt in image inpatining. Have you studied oder strategies in order to train the generator and the discriminator.Maybe both at the same iteration ....

**Comment by windj007** [comment]
>  what it does is train at each iteration one time the generator and the other the discrimantor?

Correct.

> Have you studied oder strategies in order to train the generator and the discriminator.Maybe both at the same iteration ....

No, we have not explored other strategies, e.g. updating generator and discriminator within a single step.

**Comment by windj007** [comment]
I'm closing the issue for now. If you have any other questions, feel free to reopen it or create a new one.
