### ISSUE TITLE
Random Mask Generation 

### ISSUE THREAD

**Issue by ZeeRizvee** [saic-mdal/lama#103]
Can you please guide over how can random masks be created on custom images? The link to the script given in the description does not seem to be working.

**Comment by windj007** [comment]
Hi! Could you please describe your problem in more detail? What link is broken?

If you have an environment set up, you can use script

    bin/gen_mask_dataset.py configs/data_gen/<config_name>.yaml \
        <dir with input images> <where to store image crops and masks>

Alternatively, there is a convenience wrapper via docker - please refer [to the readme](https://github.com/saic-mdal/lama#generate-different-kinds-of-masks).

**Comment by ZeeRizvee** [comment]
Thank you for the help! Is there also an option to draw the mask on top of the image, like the one which is used in Google Colab demo?

**Comment by windj007** [comment]
No, we do not provide any UI except those in Colab.

**Comment by windj007** [comment]
You can try [third-party apps](https://github.com/saic-mdal/lama#non-official-3rd-party-apps), e.g. [lama-cleaner](https://github.com/Sanster/lama-cleaner).

**Comment by windj007** [comment]
When I needed to quickly draw a mask, I used GIMP several times - just load an image, create another transparent layer, draw a mask there and save it to a separate file. Note that all masks must be strictly binary before feeding them to LaMa - thus if you make them with GIMP, you need a separate binarization step (that's pretty easy to do with cv2 and plain numpy).

**Comment by ZeeRizvee** [comment]
Thank you so much for the help and advice! Much appreciated :)

**Comment by windj007** [comment]
Note about mask binarization: `predict.py` actually does binarization - I forgot about [this line](https://github.com/saic-mdal/lama/blob/main/bin/predict.py#L75). But anyway, as stated in [another issue](https://github.com/saic-mdal/lama/issues/90#issuecomment-1096546871), having smooth masks is meaningless and it's better to control it manually.

**Comment by windj007** [comment]
You're welcome!
