### ISSUE TITLE
LAMA-Magic-Eraser-Local  for Windows 

### ISSUE THREAD

**Issue by zhaoyun0071** [saic-mdal/lama#110]
https://github.com/zhaoyun0071/LAMA-Magic-Eraser-Local

This is the local version of LAMA by PyQt5，any Windows user can use it directly without any python envrioment offline 。

**Comment by windj007** [comment]
Hi! Thank you! I'll add your app to our readme.

BTW, there is a thin artifact left after inpainting of the image with a boat on a sunset - I'd recommend dilating (extending) mask slightly before inpainting to resolve such artifacts. It might worth providing such a parameter (width of mask extension) to user.

Do you plan to release an English version of README and the application?

**Comment by zhaoyun0071** [comment]
> 

thanks for advice
i will release an English version of README and the application  a few days later
