### ISSUE TITLE
custom masks

### ISSUE THREAD

**Issue by eliohead** [saic-mdal/lama#119]
Has anyone managed to train using custom masks instead of making the script generate random ones?

**Comment by windj007** [comment]
HI! Could you please clarify you question? Pre-generated masks are not used to train LaMa - masks are generated on the fly. Readme notes "generate masks" in context of generating masks and fixing them for validation purposes.

**Comment by eliohead** [comment]
I was referring to training with user supplied masks. but I just gave a second look and found what I was searching for is already there. my bad.

**Comment by spin0r** [comment]
Sorry for asking, but how did you manage to train on user supplied masks?

**Comment by improgress** [comment]
I have been thinking about this problem, have you solved it？

**Comment by spin0r** [comment]
@improgress Unfortunately not (yet). But I'll look more into it soon.

**Comment by improgress** [comment]
OK thanks. look forward to your good news！



发自我的iPhone


------------------ Original ------------------
From: Nils Bochow ***@***.***&gt;
Date: Tue,Aug 16,2022 6:04 PM
To: saic-mdal/lama ***@***.***&gt;
Cc: improgress ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [saic-mdal/lama] custom masks (Issue #119)

**Comment by spin0r** [comment]
@improgress I managed to train with custom masks. If you are interested in my solution, contact me.

**Comment by improgress** [comment]
sure! an interesting job! im willing to learning your solution!



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Nils ***@***.***&gt;; 
发送时间: 2022年8月25日(星期四) 下午3:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [saic-mdal/lama] custom masks (Issue #119)





 
@improgress I managed to train with custom masks. If you are interested in my solution, contact me.

**Comment by HappyYuji** [comment]
@NilsBochow Thank you!
