### ISSUE TITLE
Colab Code FileNotFoundError When Running Unmodified Example

### ISSUE THREAD

**Issue by Casey-J-Wolcott** [saic-mdal/lama#121]
Hello,

I was trying to get the google colab code for this project to run its example, but it seems to be broken. 
I can run the first cell with no issues, then uncomment an example line for fname, and draw on the image to make a mask. When I click finish, it successfully shows the mask, image, and img * mask, but then gives FileNotFoundError and as such, No such file or directory: '/content/output/1010286_mask.png'

Just wondering if this project is depreciated or if its still supposed to be usable?

![image](https://user-images.githubusercontent.com/70279096/169705110-77852e56-fe02-4395-895b-6fec3fe8b6fb.png)

Also if I look through the code there are several Invalid character "\u21" in token errors involving the !PYTHONPATH lines.

**Comment by shashankvasisht** [comment]
I have the same issue @Casey-J-Wolcott . Any updates ?

**Comment by shashankvasisht** [comment]
@[senya-ashukha](https://github.com/senya-ashukha) can u please help us?

**Comment by senya-ashukha** [comment]
Hi @Casey-J-Wolcott @shashankvasisht, sorry for the late response! I will take a look tomorrow!

**Comment by ckhan101** [comment]
Yep - inpainting not outputting image to a content folder - any solutions?

**Comment by senya-ashukha** [comment]
Hi @shashankvasisht @ckhan101 !

Huge thanks for reporting! Fixed it. Torch installation got broken somehow .. https://discuss.pytorch.org/t/runtimeerror-cudnn-error-cudnn-status-not-initialized/115286

**Comment by shashankvasisht** [comment]
@senya-ashukha I believe the problem has re-occurred. Can you please take a look ?

**Comment by senya-ashukha** [comment]
@shashankvasisht I will fix it early next week!

**Comment by yx-chan131** [comment]
@senya-ashukha Hi I face the same problem. Can you check the colab code again?

**Comment by senya-ashukha** [comment]
Hi @yx-chan131, 

Thank you for reporting. Try to replace "% cd /content/lama" with "%cd /content/lama". It worked in my case. 
I no longer work at Samsung, so I cannot commit to the repo.

Best,
