### ISSUE TITLE
Cannot generate different kinds of masks

### ISSUE THREAD

**Issue by miaodd98** [saic-mdal/lama#126]
Hello! Appreciate your code sharing!
I followed the tips in your introductions but what I got is only  a sentence of : Detectron v2 is not installed. And the code's output is nothing, the folder is still empty.
I checked other issues and found this sentence is nothing to do with the codes.
I tried both commands on "Create your data" and "Hints" parts, and nothing happened.
Could you please check my issue and propose any of ideas for that? Many thanks!

**Comment by miaodd98** [comment]
OK I just double check that I have followed the right hints but got nothing when running the codes. Could anyone help me out for generating these masks? Many thanks!

**Comment by miaodd98** [comment]
Problem solved. 

> python3 bin/gen_mask_dataset.py \
$(pwd)/configs/data_gen/random_<size>_512.yaml \ # thick, thin, medium
my_dataset/val_source/ \
my_dataset/val/random_<size>_512.yaml \# thick, thin, medium
--ext jpg

The last parameter "--ext" MUST BE the same format of the original images.  This is introduced in gen_mask_dataset.py but not introduced/noted in the README.

**Comment by forwhom1212** [comment]
> Hello! Appreciate your code sharing! I followed the tips in your introductions but what I got is only a sentence of : Detectron v2 is not installed. And the code's output is nothing, the folder is still empty. I checked other issues and found this sentence is nothing to do with the codes. I tried both commands on "Create your data" and "Hints" parts, and nothing happened. Could you please check my issue and propose any of ideas for that? Many thanks!

Same problem.😭
