### ISSUE TITLE
A small question about Gan_loss

### ISSUE THREAD

**Issue by q671383789** [saic-mdal/lama#134]
Thx for ur great work, But I'm confused about the Gan loss, 
![image](https://user-images.githubusercontent.com/48686306/179642133-4f9e8210-29b6-40a3-814a-9607e3047510.png)
Should if the patch is real to be one and fake to be zero? but this seems do it in the opposite way, 
could u explain for me , thx

**Comment by hughkhu** [comment]
Also confused about the GAN loss. Have u figure out？
