### ISSUE TITLE
Fixed user-generated masks for training

### ISSUE THREAD

**Issue by spin0r** [saic-mdal/lama#147]
Hi,

is there a way to specify user-generated masks for the training instead of creating them on the fly? I know that @eliohead asked the same already (#119) , but I can't figure out if it is already implemented or if I have to do it on my own. 

Thank you!

**Comment by spin0r** [comment]
I solved it. If someone is interested, just contact me.

**Comment by lucDoom** [comment]
> I solved it. If someone is interested, just contact me.

sir, I wonder the same question.plz tell me how to do this, thanks a lot!

**Comment by spin0r** [comment]
@lucDoom Hi, look at my forked repository and compare with the main branch. You have to modify the mask part of the code and have your pre-generated masks in an h5-file (my solution). If you don't understand what I did, just ask again.

**Comment by NilsBochow** [comment]
@YZ00192 Hi, 
check out my fork and the issue in there. There I explain briefly what to change.

**Comment by amangupta2303** [comment]
@NilsBochow Thank you for your contribution. I am able to understand what you did to create mask and input that mask for training instead of training with auto-generated masks. Can you explain in brief what to change.

**Comment by ZMHANDWYB** [comment]
> 嗨，查看我的 fork 和那里的问题。在那里，我简要解释了要更改的内容。
Hi, hello. I haven't found what you mentioned. Could you tell me in detail how you did it? I don't quite understand how you did it.
