### ISSUE TITLE
About the training command

### ISSUE THREAD

**Issue by yumengWang112** [saic-mdal/lama#161]
python3 bin/train.py -cn lama-fourier-celeba data.batch_size=10

sorry for my poor english!
I wonder what's the "-cn lama-fourier-celeba" means?  
when i ran by this command,it made an error,
 
**In 'lama-fourier-celeba': Could not find 'location/celeba'

Available options in 'location':
        celeba_example
        docker
        places_example
Config search path:
        provider=hydra, path=pkg://hydra.conf
        provider=main, path=file:///home/featurize/work/lama-main/configs/training
        provider=schema, path=structured://

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.**

**Comment by dragen1860** [comment]
cn: maybe convolution network.

**Comment by yumengWang112** [comment]
> 

Thanks a lot! I have fixed this problem,maybe cn means config name.
and i find the lama-fourier-celeba.yaml ,and tere are some parameters need to change.

**Comment by dragen1860** [comment]
@yumengWang112 yeah, config name looks more reasonable!
thy the way, do you know `ablv2` means?  i found it appears in many config file name.

**Comment by micklexqg** [comment]
> > 
> 
> Thanks a lot! I have fixed this problem,maybe cn means config name. and i find the lama-fourier-celeba.yaml ,and tere are some parameters need to change.

@yumengWang112  how did you solve it, what need to be changed?
