### ISSUE TITLE
No module named 'saicinpainting'

### ISSUE THREAD

**Issue by inhahe** [saic-mdal/lama#164]
When I follow the instructions, at the predict stage, I get:

(lama) inhahe@inhahe-Z370-AORUS-Gaming-5:~/lama$ python3 bin/predict.py model.path=$(pwd)/big-lama indir=$(pwd)/LaMa_test_images outdir=$(pwd)/output
Traceback (most recent call last):
  File "bin/predict.py", line 14, in <module>
    from saicinpainting.evaluation.utils import move_to_device
ModuleNotFoundError: No module named 'saicinpainting'

I'm using miniconda.
a saicinpainting directory exists under the current directory. Apparently Python doesn't want to load modules from the current directory.

**Comment by inhahe** [comment]
I did 'cp -r saicinpainting bin' and 'cp -r models bin' and now it works.

**Comment by inhahe** [comment]
Oh, nevermind, I just noticed 'export PYTHONPATH=$(pwd)' in the instructions, I must have quit and reopened terminal and not re-executed that command.

**Comment by yaopengfei1** [comment]
you can  consider export PYTHONPATH=$(pwd):${PYTHONPATH}

**Comment by SalmaSalahh** [comment]
> When I follow the instructions, at the predict stage, I get:
> 
> (lama) inhahe@inhahe-Z370-AORUS-Gaming-5:~/lama$ python3 bin/predict.py model.path=$(pwd)/big-lama indir=$(pwd)/LaMa_test_images outdir=$(pwd)/output Traceback (most recent call last): File "bin/predict.py", line 14, in from saicinpainting.evaluation.utils import move_to_device ModuleNotFoundError: No module named 'saicinpainting'
> 
> I'm using miniconda. a saicinpainting directory exists under the current directory. Apparently Python doesn't want to load modules from the current directory.

I also have this problem, so can you tell me how did you fix it please ?

**Comment by inhahe** [comment]
> I also have this problem, so can you tell me how did you fix it please ?

I think the problem was that I needed to do `export PYTHONPATH=$(pwd)`, then exit the terminal, then load it again, then run the program. If that doesn't work, `cp -r saicinpainting bin` and `cp -r models bin` should work.

**Comment by SalmaSalahh** [comment]
src/tcmalloc.cc:283] Attempt to free invalid pointer 0x7f297cb0fd98

Do you know how to fix this ?

**Comment by Firdavs-coder** [comment]
I have faced that error. I fixed it. First copy `predict.py` from bin folder and paste to lama fodler. That is replace path the `predict.py` from bin to lama folder. I think it works
