### ISSUE TITLE
RuntimeError: CUDA error: invalid device ordinal

### ISSUE THREAD

**Issue by inhahe** [saic-mdal/lama#165]
When I try to run 'python3 bin/predict.py refine=True model.path=$(pwd)/big-lama indir=$(pwd)/LaMa_test_images outdir=$(pwd)/output', I get 'RuntimeError: CUDA error: invalid device ordinal'. It worked before, now it doesn't. I have no idea why.

**Comment by lucDoom** [comment]
> When I try to run 'python3 bin/predict.py refine=True model.path=$(pwd)/big-lama indir=$(pwd)/LaMa_test_images outdir=$(pwd)/output', I get 'RuntimeError: CUDA error: invalid device ordinal'. It worked before, now it doesn't. I have no idea why.

I met the same question.I think the season is now you are using more than 1 gpu, but one of them is integrated graphics.

**Comment by inhahe** [comment]
Ok, I hope a fix can be issued for this, if possible. If it's not possible to guess which is the correct GPU, maybe ask the user. Failing that, I'd like to know how to fix this myself..

**Comment by lucDoom** [comment]
> Ok, I hope a fix can be issued for this, if possible. If it's not possible to guess which is the correct GPU, maybe ask the user. Failing that, I'd like to know how to fix this myself..

in configs/prediction/default.yaml, you can set  gpu_ids for ur own device.

**Comment by inhahe** [comment]
thanks, i'll try that later.

**Comment by inhahe** [comment]
The instructions in the file said to change it it from 0,1 to 0, if you only have one gpu, which I did, and it worked. Not sure why the default is to assume you have exactly two gpus. Or why it worked the first time I ran it before I changed it.

**Comment by windj007** [comment]
Two gpus are really needed only when you use refinement: it requires at least 24gb VRAM. If you do not use refinement, you can infer on a single gpu
