### ISSUE TITLE
Evaluation Metrics

### ISSUE THREAD

**Issue by alexerupakat** [saic-mdal/lama#170]
Hai Can you tell me how the FID  and other metrics are obtained . did you take the mean value ?

**Comment by cohimame** [comment]
Hello!

If you are asking how to compute the FID metric in general, check out this doc, for example:
https://torchmetrics.readthedocs.io/en/stable/image/frechet_inception_distance.html

And this article:
https://wandb.ai/ayush-thakur/gan-evaluation/reports/How-to-Evaluate-GANs-using-Frechet-Inception-Distance-FID---Vmlldzo0MTAxOTI

And original paper where the FID was introduced:
https://papers.nips.cc/paper/2017/file/8a1d694707eb0fefe65871369074926d-Paper.pdf

We also cover this question in the following section:
https://github.com/saic-mdal/lama#places

![Uploading Screenshot_20221226_172828.png…]()
