### ISSUE TITLE
On the role of 1 * 1 convolution

### ISSUE THREAD

**Issue by song201216** [saic-mdal/lama#172]
Dear author, thank you for your great work, but I have a question.Why after Fourier transform using convolution operation？What is the function of convolution operator in here?Thank you very much for you can answer my question!
![屏幕截图 2022-10-21 103016](https://user-images.githubusercontent.com/73896789/197100477-03ac93db-f85c-42eb-8ecf-fb6f75458b81.png)

**Comment by windj007** [comment]
Hi! this is just an ordinary `nn.Conv2d(kernel=1)`. The role is to adapt global features for mixing with local2global conv (the second from the left). I believe, it might be unnecessary on some datasets
