### ISSUE TITLE
512*512 celebahq test

### ISSUE THREAD

**Issue by Ellohiye** [saic-mdal/lama#174]
Hello author! Thanks for your wonderful work!
Regarding the celebahq dataset, I have a question. The training uses a resolution of 256*256 for training. Can we use 512*512 size images for testing? Which hyperparameters of the code should I modify if high-resolution testing is possible?
Looking forward to your reply! Thanks!

**Comment by windj007** [comment]
All our experiments are already configured in such a way so the data on disk is 512x512. It is cropped and resized on-the-fly for training - but for validation it is loaded as is.

**Comment by windj007** [comment]
Validation should also work with higher-resolution images out-of-the-box.
