### ISSUE TITLE
Training issues:#@Userwarning: In 'hydra/overrides': Usage of deprecated keyword in package header ' package _group_'

### ISSUE THREAD

**Issue by Giri0808** [saic-mdal/lama#179]
This problem occurs when training either my own dataset or the CeleA dataset, and I would like to ask how to solve it.
(lama) w@w:~/lama$ python3 bin/train.py -cn lama-fourier location=my_dataset data.batch_size=10
Detectron v2 is not installed
/home/w/miniconda/envs /lama/lib/python3.6/site-packages /hydra/core/default_element.py:127: Userwarning: In 'hydra/overrides': Usage of deprecated keyword in package header '#@package _group_'.
See https://hydra.cc/docs/next/upgrades/1.0_to_1.1/changes_to_package_header for more infornation 
See {url} for more information" " "

**Comment by cohimame** [comment]
Hello!
Check you hydra version: 
https://github.com/saic-mdal/lama/blob/main/requirements.txt
pip install hydra-core==1.1.0

**Comment by Giri0808** [comment]
Thank you very much, the problem is solved.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月27日(星期二) 凌晨2:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [saic-mdal/lama] Training ***@***.***: In &#39;hydra/overrides&#39;: Usage of deprecated keyword in package header &#39; package _group_&#39; (Issue #179)





 
Hello!
 Check you hydra version:
 https://github.com/saic-mdal/lama/blob/main/requirements.txt
 pip install hydra-core==1.1.0

**Comment by qwexacc** [comment]
> 你好！
> 
> 检查你的 hydra 版本，这个版本不应该导致这个错误： `pip install hydra-core==1.1.0`
> 
> https://github.com/saic-mdal/lama/blob/main/requirements.txt



> pip install hydra-core==1.1.0

Hello, my version is this official version, but there is still this error, I wonder if you can help me?

**Comment by Giri0808** [comment]
谢谢，这个问题好像解决了，是configs没修改好的原因




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年4月13日(星期六) 中午11:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [advimman/lama] Training ***@***.***: In &#39;hydra/overrides&#39;: Usage of deprecated keyword in package header &#39; package _group_&#39; (Issue #179)














  
你好！
 
检查你的 hydra 版本，这个版本不应该导致这个错误： pip install hydra-core==1.1.0
 
https://github.com/saic-mdal/lama/blob/main/requirements.txt
   
pip install hydra-core==1.1.0
  
Hello, my version is this official version, but there is still this error, I wonder if you can help me?
