### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by lyu124** [saic-mdal/lama#180]
Hello. I was trying to training the network with my own data, which is with the size of 512*512. I am using a server with 4 GPUs. During the training, the CUDA out of memory problem always occurs. I have already tried to use smaller batch_size. But only with data.batch_size=1 reports no problem, but it is not practical. 
I have also tried to change increment operator to normal ones, but still comes this problem.
Is there maybe any other ways, which can solve this problem? 
Thank you so much!

**Comment by shallweiwei** [comment]
I have also faced these problems,you can see that each gpu need to deal with 1 picture,and the memory usage of the first gpu increases with the number of Gpus

**Comment by cohimame** [comment]
Hello! 
Could you provide more information:
1. nvidia-smi with the information on your GPUs (how much memory they have)
2. The config that you are using for training.

**Comment by windj007** [comment]
Core LaMa feature is generalization to higher resolution and larger masks than it saw during training. You can train in 256 and then use it with 512 at inference stage. However, you will need to tune augmentations (mainly random scale and crop) for your case. Our default training augmentations are set for exactly that scenario: original data in 512, but training in 256 (using only crops) - but they might be not optimal for your case

**Comment by windj007** [comment]
You can also experiment with mixed precision training, e.g. bf16 - but be careful: the training might become unstable. There are tricks to stabilize it: bf16, manual mixed precision, smaller learning rate, plenty of them. We have not tried training lama in reduced precision. If it works, you can save up to 50% memory.

Alternatively, you can experiment with virtual batch aka gradient accumulation. Large effective batch is critical for LaMa training -- with batch size of 4 it will perform much worse than it could be.
