### ISSUE TITLE
Bad result in some situations

### ISSUE THREAD

**Issue by DanielZanchi** [saic-mdal/lama#181]
I am getting bad outputs in some situations.
What could be done to avoid this? 

<img src="https://user-images.githubusercontent.com/6886116/202917417-4d2f38cd-7cb9-4ec4-ad86-18a5983bafab.png" width=50% height=50%>
<img src="https://user-images.githubusercontent.com/6886116/202917419-fb3299fd-e48a-453f-bce5-5f93cfc0feb0.png" width=50% height=50%>
<img src="https://user-images.githubusercontent.com/6886116/202917682-d7cdbca7-e096-4ece-827a-2e334f282645.png" width=50% height=50%>

**Comment by windj007** [comment]
Binarize your mask before feeding it to LaMa. The mask must contain only 0s and 255s
