### ISSUE TITLE
Why does the edge inpainting results blur?

### ISSUE THREAD

**Issue by Luciawow** [saic-mdal/lama#189]
I have been trying to apply LaMa to facade texture repair, the occlusion like trees and buildings always located at the edge of the facade, and the results seem to blur as below:
![wall-010_mask(1)](https://user-images.githubusercontent.com/115792756/205927354-dde05de3-19d8-4b82-9c24-1d5323b1b504.png)
the original image:
![wall-010](https://user-images.githubusercontent.com/115792756/205927523-9ef960f6-3aa0-425e-8e87-292212cd8637.png)
What should I do to make the fluzzy clearer?

**Comment by windj007** [comment]
LaMa is not very good at outpainting out-of-the-box (when the mask is completely on the border of the image). If you can provide more context to the image and turn it to inpainting, it will be better.
