### ISSUE TITLE
error saicinpainting

### ISSUE THREAD

**Issue by huyhumg-vn98** [saic-mdal/lama#191]
![image](https://user-images.githubusercontent.com/77087472/206149945-f60eb5f6-34dd-40cb-9538-6cdf2eb61772.png)

**Comment by lyu124** [comment]
hi, maybe you can try to move saicipainting directory to bin directory like cp -r saicinpainting bin. It worked for me.

**Comment by cohimame** [comment]
Hello @huyhumg-vn98!

Could you try the following command  inside lama/ folder? Does it work in MINGW on your system?
>cd lama/
> export TORCH_HOME=$(pwd) && export PYTHONPATH=$(pwd)

**Comment by windj007** [comment]
This error has nothing to do with LaMa, it is the matter of basic Python usage. To be able to import something, it needs to be on PYTHONPATH - either you need to install it via pip or add to PYTHONPATH manually. We do not provide a pip-installable package, so you need the latter way `export PYTHONPATH="absolute-path-to-lama-repo"`
