### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'big-lama\\config.yaml'

### ISSUE THREAD

**Issue by Firdavs-coder** [saic-mdal/lama#192]
![image](https://user-images.githubusercontent.com/84655445/206693031-0b021373-ad41-4e0c-9693-08755b273be4.png)
Hi, I am facing a issue like that. I changed 'big-lama' folder name to 'big_lama' and there is config.yaml file in that directory but it faced issue

**Comment by Firdavs-coder** [comment]
> ![image](https://user-images.githubusercontent.com/84655445/206693031-0b021373-ad41-4e0c-9693-08755b273be4.png) Hi, I am facing a issue like that. I changed 'big-lama' folder name to 'big_lama' and there is config.yaml file in that directory but it faced issue

![image](https://user-images.githubusercontent.com/84655445/206693307-d8ef0cd8-d241-4c16-a5ff-ea57b20426dc.png)
My folder image

**Comment by lyu124** [comment]
Hi, maybe you can try to write the full absolute path of big-lama like /Users/777/Desktop/lm2/lama/big-lama, where you have downloaded big-lama, when  running the python file.

**Comment by Firdavs-coder** [comment]
Thanks everyone. I fixed it. `../../big_lama/config.yaml`

**Comment by Firdavs-coder** [comment]
Thanks everyone. I fixed it. ../../big_lama/config.yaml

**Comment by Firdavs-coder** [comment]
Thanks everyone. I fixed it. ../../big_lama/config.yaml
