### ISSUE TITLE
Google Colab: Output not saved in /content/output

### ISSUE THREAD

**Issue by pmy0792** [saic-mdal/lama#197]
I've tried to run the google colab .ipynb file, but have been facing error below:
FileNotFoundError: [Errno 2] No such file or directory: '/content/output/1224276_original_mask.png'

I used both local image file and example image file, and none of them works.

I had searched for relevant issues but none of them solved the error.
#82

**Comment by cohimame** [comment]
Fixed!

**Comment by cohimame** [comment]
Looks like colab do not accept spaced commands i.e.:
`! mkdir`  - fail
`!mkdir` - win

**Comment by AceEcho** [comment]
Same, seems colab does not support spaced command.

**Comment by MacM2Pro** [comment]
I'm sorry, but this doesn't fix the bug

> Looks like colab do not accept spaced commands i.e.: `! mkdir` - fail `!mkdir` - win
> 
> And there were couple of them in notebook
