### ISSUE TITLE
Spectral Transform block

### ISSUE THREAD

**Issue by phongnhhn92** [saic-mdal/lama#2]
Hi guys,
I have a question related to your Spectral Transform block. If I understand correctly then this block has been introduced in this Fast Fourier Convolution [paper](https://papers.nips.cc/paper/2020/hash/2fd5d41ec6cfab47e32164d5624269b1-Abstract.html). I wonder what is the difference ? 
I found their implementation here: https://github.com/pkumivision/FFC/blob/ac66fd7ded8e1358de18c31590b141f20988fcd3/model_zoo/ffc.py#L71
However, this code is not working on the lastest Pytorch 1.9. Are u using similar function in your work ?

Best regards,
Phong

**Comment by windj007** [comment]
Hi Phong,

Yes, that's the right paper. We started with their implementation (your link is correct) and tweaked so it works with recent pytorch. 

Line 54 has to be changed from

    ffted = torch.rfft(x, signal_ndim=2, normalized=True)

to:

    ffted = torch.fft.rfft(x, dim=(-2, -1), norm="ortho")
    ffted = torch.stack((ffted.real, ffted.imag), dim=-1)

Line 65 has to be changed from

    output = torch.irfft(ffted, signal_ndim=2, signal_sizes=r_size[2:], normalized=True)

to:

    ffted = torch.complex(ffted[..., 0], ffted[..., 1])
    output = torch.fft.irfftn(ffted, s=x.shape[-2:], dim=(-2, -1), norm="ortho")

Except those tweaks, that should be pretty same code.

**Comment by phongnhhn92** [comment]
Hi, 

That's perfect ! I will try it out. 
I will close this issue for now. Thank you so much !

**Comment by phongnhhn92** [comment]
Hi @windj007, I would like to resurface on this issue and ask you a few questions. 

1) I am trying to implement your Fast Fourier Conv Residual blocks and I was so surprised to see that those blocks are only in the bottleneck between encoder and decoder. Do you think we can achieve better results if we put those blocks there in the encoder part ? 

2) In the Figure 2 of your paper, I do not see any skip connections between encoder and decoder. I wonder if you omit it or you do not use them at all in your model ?

**Comment by phongnhhn92** [comment]
Hi,
Btw i tried the code and it seems like there is still an error on both [TORCH.FFT.RFFT](https://pytorch.org/docs/1.9.0/generated/torch.fft.rfft.html) and [TORCH.FFT.IRFFTN](https://pytorch.org/docs/1.9.0/generated/torch.fft.irfftn.html#torch.fft.irfftn) function.

In your code:
```
ffted = torch.fft.rfft(x, dim=(-2, -1), norm="ortho")
ffted = torch.stack((ffted.real, ffted.imag), dim=-1)
```
This is the error I got:
`TypeError: fft_rfft(): argument 'dim' must be int, not tuple`

If you check the current API then dim is a int not a tuple.

**Comment by windj007** [comment]
My bad, the correct function name is rfft**n**, not rfft. Same is for irfft**n**.

**Comment by windj007** [comment]
> Do you think we can achieve better results if we put those blocks there in the encoder part ?

We tried that and it did not help significantly. However, it may depend on the task and the tuning. We are going to revisit this decision.

> I wonder if you omit it or you do not use them at all in your model ?

We do not use skip connections from encoder directly to decoder, because ResNet learns identity easily without them. Such far skip connections significantly increase memory consumption on inference, so this might be impractical.

> it seems like Resnet50 + dilation (trained on segmentation task) produces the best results. However, I do not understand the connection between this pretrained model and the Fourier convolution.

> Do you modify the above pretrained model with Fourier Convolution and train it again for the semantic segmentation task.

Table 3 is about different architectures of perceptual loss backbone. In the PL backbones, we use only pretrained models as-is without changing weights. There are no Fourier convolutions in the PL backone. The only modification to PL backbone we make is making some of the convolutions dilated in "Resnet50 + dilation".

**Comment by phongnhhn92** [comment]
<img width="538" alt="Screenshot 2021-09-22 at 21 58 53" src="https://user-images.githubusercontent.com/11288381/134413297-b808ab70-d88c-447d-b2c1-87af44077823.png">
One more question: if I have a feature map size B,C,H,W then do i have to split them in half and feed each one of them to two different branches ? Or the green and pink block are the same tensor ?
