### ISSUE TITLE
An implementation using LaMa and MaskDINO: Mask LaMa

### ISSUE THREAD

**Issue by qwopqwop200** [saic-mdal/lama#200]
hello. thank you for your work
I would like to share an app that uses [MaskDINO](https://github.com/IDEA-Research/MaskDINO) and Lama.
https://github.com/qwopqwop200/lama-with-maskdino
Here's a simple example.
![demo](https://user-images.githubusercontent.com/64115820/211523076-117ec3da-f344-44eb-b0e2-a62f64f31402.gif)

**Comment by windj007** [comment]
Thank you!
