### ISSUE TITLE
Is FFC carried out in the early layers as the ratio for global is set 0? 

### ISSUE THREAD

**Issue by micklexqg** [saic-mdal/lama#211]
Hi, I find the ratio_gin and ratio_gout is set 0 for init_conv_kwargs and downsample_conv_kwargs, so I wonder is FFC carried out in the early layers or just in the middle bottleneck?

**Comment by windj007** [comment]
In the paper, FFC is only enabled in the bottleneck - but you can also enable it in downsample and upsample blocks - it often helps

**Comment by micklexqg** [comment]
> In the paper, FFC is only enabled in the bottleneck - but you can also enable it in downsample and upsample blocks - it often helps

Thanks
