### ISSUE TITLE
Error while training on CelebA dataset

### ISSUE THREAD

**Issue by abbhinavvenkat** [saic-mdal/lama#22]
Hi Team Lama, 

I've setup the CelebA dataset and begun training using the same command indicated in your [Readme](https://github.com/saic-mdal/lama#celeba). The model trains for half an epoch and then throws the following error in the evaluation step - 

`RuntimeError: stack expects each tensor to be equal size, but got [3] at entry 0 and [1] at entry 1997` 

I have only worked on generating the CelebA data and the config file; the rest of the repository is untouched. I'm attaching the config and training log file generated by your model. Do let me know if you have some insight into why this might be happening. 

[train.log](https://github.com/saic-mdal/lama/files/7373708/train.log)
[config.txt](https://github.com/saic-mdal/lama/files/7373628/config.txt)

Thanks!
 
Abbhinav

**Comment by cohimame** [comment]
Yep, error is still there, i'm working on it.

**Comment by abbhinavvenkat** [comment]
Hi! I've pulled the latest code and it works now! Thanks!
