### ISSUE TITLE
Use license

### ISSUE THREAD

**Issue by 18201117** [saic-mdal/lama#38]
I want to use your technology to build a website to help people modify pictures. I won't use it for revenue. I'll point out the source. Can I get your permission?I will be deeply grateful。

**Comment by windj007** [comment]
Hi! Thank you for your interest! Main code in this repo is licensed under Apache-2.0, which is very permissive - so you can assemble an app based on it.

Btw, there is a very good and free app based on LaMa Inpainting - https://cleanup.pictures/ - maybe it already satisfies your needs?

**Comment by 18201117** [comment]
Thank you for your reply!I'll try the program you recommend.

**Comment by elimohl** [comment]
@18201117 if you make the website, please share the link with us.
