### ISSUE TITLE
Can I train a smaller model?

### ISSUE THREAD

**Issue by napohou** [saic-mdal/lama#39]
Hi authors,
Thanks for sharing the code. I find the sizes of your models are about 290M to 390M. It is too large. Can we do some modifications to train a smaller model such as <100M?

**Comment by windj007** [comment]
Hi! Thank you for your interest.
Sure, you can train a smaller model, but expect some performance drop. We cannot help you with model compression and anythin production-related due to the policies of our company.

**Comment by napohou** [comment]
I see. Let me do some investigation. Thanks for the amazing work! Do we have any direction for a better performance in future?
