### ISSUE TITLE
Question on masked_l1_loss

### ISSUE THREAD

**Issue by lovecambi** [saic-mdal/lama#46]
For the function `masked_l1_loss` (https://github.com/saic-mdal/lama/blob/main/saicinpainting/training/losses/feature_matching.py#L13), 
I found ` weight_known=10` and `weight_missing=0` in all config yaml files, so the masked_l1_loss won't calculate the difference on masked region. This seems counter-intuitive. Can you explain the reason?

**Comment by windj007** [comment]
Hi Sorry for late reply

No, there is no reason. L1 is only applied to the known part of the image and to the best of our knowledge, does not affect training. It is there just for historical reasons. You can turn L1 loss off altogether and everything should be fine
