### ISSUE TITLE
no yaml file

### ISSUE THREAD

**Issue by wly-ai-bj** [saic-mdal/lama#48]
hydra.main(config_path='../configs/training', config_name='tiny_test.yaml')

where is the config file? configs/training/tiny_test.yaml does not exist.

**Comment by windj007** [comment]
Hi! There isn't such a config in the public repo. Please choose any other config via `./bin/train.py -cn <config_name>`, where `config_name` is a file name within `configs/training` folder, e.g. `ablv2_work_md`
