### ISSUE TITLE
How to use ddp during training

### ISSUE THREAD

**Issue by Queenyy** [saic-mdal/lama#49]
Hi, I use the Places365-Standard dataset to train the model, which has more than 1.8 Million images. And when i set batch_size=15, accelerator=ddp, gpus=8, from my experience the batchs in one epoch is `1.8M/15/8`,  each gpu just gets visibility into a subset of the overall dataset. But i found that the batchs on each gpu is `1.8M/15` in lama.
 I run `python3 bin/train.py -cn mylama-fourier` to start training. 
Is this the right way to use ddp to accelerate training?

**Comment by windj007** [comment]
Hi!

Our pipeline uses DDP by default, so no extra configuration is needed. With DDP enabled, `data.batch_size` sets number of samples per GPU - so the total batch size will be `data.batch_size * n_gpus`. For a more fine-grained tuning, please refer to `trainer.kwargs` subsection of the configuration.

Does this answer your question?

Btw, what is `180w+`?

**Comment by Queenyy** [comment]
Hi, thanks for your reply. 

There is also a parameter named `limit_train_batches` in `trainer.kwargs`, is this the number of samples per GPU?  So for one epoch the number of samples is `limit_train_batches * n_gpus`?

PS: Please ignore this mistake `180w`, what i mean is `1.8 Million`, i have edit the question.

**Comment by windj007** [comment]
`limit_train_batches` is the number of training steps within a single epoch. It is independent from batch size. I believe that you do not have to alter it unless your dataset is really small (`dataset_size < limit_train_batches * n_gpus * batch_size`).

Set it to balance between amount of training and evaluation frequency. We set it so validation is conducted approximately 4 times a day - so each day we have some news, but no excessive time spent on too frequent evaluation. For our hardware it was 25000.

If the training is unstable, then the epoch size should be smaller (not to miss a good local minimum). This might be the case for purely adversarial models, shouldn't be so for LaMa.

Note that there is another parameter `val_check_interval`, which should be almost always be equal to `limit_train_batches` (it is so in our configs).

**Comment by Queenyy** [comment]
I use the 512 Places2 datasets, and bs=10, n_gpus=8 and ddp accelerator, limit_train_batches=25000, the network is the same as the lama-fourier in your release model, it takes approximately 6h an epoch, is this normal? I am wondering how long it takes during your experiments and the corresponding batchsize? Are there some time-consuming optimization directions? Thanks very much!

**Comment by windj007** [comment]
>  bs=10

Do you mean that `data.batch_size=10` and the training is running on 8 GPUs - so the total batch size is 80?

>  it takes approximately 6h an epoch, is this normal?

That sounds reasonable. Surely, it depends on the exact model of GPU and performance of HDD/SDD

**Comment by Sanster** [comment]
@Queenyy hi, Have you successfully finetuned your own lama model? I would be very grateful if you could share some experiences.

**Comment by nishanthballal-9** [comment]
Hi @windj007 
I'm training a big-lama model on a custom dataset. I trained both single GPU and multi GPU training and here are some observations I see.
Single GPU: Tesla V100 16GB: data.batch size = 6
Time taken per epoch is ~ 1 hr 12 min
Multi GPU: 4 x Tesla V100 16 GB: data.batch_size = 6
Time taken per epoch is ~ 1 hr 8 min

Ideally one would expect the time taken per epoch to reduce when using ddp. Am I missing something here? Is there any other parameter that needs to be changed before multi gpu training?

I run `python3 bin/train.py -cn big-lama data.batch_size=6` ro start my training

**Comment by jingtianweidizzf** [comment]
> Hi @windj007
> 
> I'm training a big-lama model on a custom dataset. I trained both single GPU and multi GPU training and here are some observations I see. Single GPU: Tesla V100 16GB: data.batch size = 6 Time taken per epoch is ~ 1 hr 12 min Multi GPU: 4 x Tesla V100 16 GB: data.batch_size = 6 Time taken per epoch is ~ 1 hr 11 min (almost the same time)
> 
> Ideally one would expect the time taken per epoch to reduce when using ddp. Am I missing something here? Is there any other parameter that needs to be changed before multi gpu training?
> 
> I run `python3 bin/train.py -cn big-lama data.batch_size=6` ro start my training

Hi @nishanthballal-9 ,

did you found a solution? I think I also encountered the same problem. In my case, using multiple GPUs with DDP takes the same training time as using only 1 GPU to train a model. I wonder if something need to be modified in the source code to reduce the training time using DDP.

**Comment by IMBAfarmer09** [comment]
This seems to be caused by a bug. The problem occurred in https://github.com/advimman/lama/blob/786f5936b27fb3dacd2b1ad799e4de968ea697e7/saicinpainting/training/trainers/base.py#L130. The added parameters were not correctly loaded. It is necessary to modify the related code （not only the following line, but also some related format adjustment） to ensure that the parameters related to DDP are correctly passed.
Origin
`dataloader = make_default_train_dataloader(**self.config.data.train)`
Fixed
`dataloader = make_default_train_dataloader(**kwargs)`
