### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by Moldoteck** [saic-mdal/lama#51]
This amazing model is now integrated into a telegram bot. 
Here is the source code https://github.com/Moldoteck/MagicEraser
And here is the bot: https://t.me/MagicEraser
Here is the bot username: @MagicEraserBot

**Comment by windj007** [comment]
Hi! Thank you for you contribution!

Do you infer the mask via subtracting the colored image from the original one?

**Comment by Moldoteck** [comment]
Kind of, yes. Since Telegram is doing some compression, I apply gaussian filter in order to eliminate some distoraions, after that- substraction and some morphology in the end. Here is the code: https://github.com/Moldoteck/lama/blob/main/bin/mask.py

**Comment by windj007** [comment]
I see, thank you! Just tested it, worked well!

**Comment by senya-ashukha** [comment]
It does not work for me :(
<img width="247" alt="Screenshot 2021-11-26 at 13 57 23" src="https://user-images.githubusercontent.com/10505555/143570416-768aec1d-1ea5-4609-8811-54f1a0ed2623.png">

**Comment by Moldoteck** [comment]
Yep, of course

**Comment by Moldoteck** [comment]
I have posted a wrong link. Could you please change it to https://t.me/MagicEraserBot ?
