### ISSUE TITLE
Discriminator config

### ISSUE THREAD

**Issue by lixiaocong-svg** [saic-mdal/lama#57]
Hello, your paper mentions that the discriminator uses Fourier or dilated convolution, but I see that the discriminator is set to'pix2pixhd_nlayer' in the config files. What is the reason?

**Comment by windj007** [comment]
Hi! No, we do not use FFC/dilations in the discriminator - and the paper should not contain such info. The configs are correct.

Could you please point us to the part of the paper which causes such a confusion?

**Comment by lixiaocong-svg** [comment]
'TheφHRF(x)can be implemented using Fourier or Dilated convolutions.'
Sorry, I may have misunderstood.The cause of my misunderstanding is HRFPL loss.
But there is FFCNLayerDiscriminator in the ffc file, but it seems that it cannot be called directly. Can you tell me the reason?
Finally, thank you very much for your reply

**Comment by windj007** [comment]
> FFCNLayerDiscriminator

We just forgot to remove that piece of code before code release. It was not used to train any final models. We tried it but it was not very helpful.
