### ISSUE TITLE
lama-cleaner

### ISSUE THREAD

**Issue by Sanster** [saic-mdal/lama#59]
A self-host version of [cleanup.pictures](https://cleanup.pictures/)

https://github.com/Sanster/lama-cleaner

![example](https://github.com/Sanster/lama-cleaner/raw/main/assets/lama-cleaner-example.gif)

**Comment by windj007** [comment]
Hi @Sanster, thank you very much for your contribution!

**Comment by roimulia2** [comment]
Hey @Sanster , can I ask where did you host your model at? We tried the different solutions but every one we tried was super expensive :/

**Comment by Sanster** [comment]
> Hey @Sanster , can I ask where did you host your model at? We tried the different solutions but every one we tried was super expensive :/

If you are using lama-cleaner, the model is downloaded and deployed locally

**Comment by roimulia2** [comment]
oh okay, got it, thanks! Did you manage to get ZITS inpainting to work?

**Comment by Sanster** [comment]
> oh okay, got it, thanks! Did you manage to get ZITS inpainting to work?

You can now use [Lama Cleaner](https://github.com/Sanster/lama-cleaner/releases/tag/0.15.0) to try ZITS

**Comment by roimulia2** [comment]
Nice! Do you have a preference from performance/output quality when comparing ZITS and LaMa?

**Comment by Sanster** [comment]
I tried to find a picture to illustrate the advantages of ZITS over LaMa, but I couldn't find one that was very advantageous. The following example is from the ZITS paper.



| Original Image                                                                                                         | ZITS                                                                                                                       | LaMa                                                                                                                       |
| ---------------------------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------------------------------------- |
| ![zits_original](https://user-images.githubusercontent.com/3998421/180464918-eb13ebfb-8718-461c-9e8b-7f6d8bb7a84f.png) | ![zits_compare_zits](https://user-images.githubusercontent.com/3998421/180464914-4db722c9-047f-48fe-9bb4-916ba09eb5c6.png) | ![zits_compare_lama](https://user-images.githubusercontent.com/3998421/180464903-ffb5f770-4372-4488-ba76-4b4a8c3323f5.png) |

**Comment by roimulia2** [comment]
Okay got it, thanks. From memory/RAM and CPU usage, did you notice any difference?
