### ISSUE TITLE
there are some strange white areas in my result.

### ISSUE THREAD

**Issue by liangzimei** [saic-mdal/lama#68]
Thanks for your exciting work firstly.
when i use `-cn lama-fourier ` to train my own dataset .  i find there  are some white areas in some train and test images (not all images, and according to my observation it is irrelevant to mask size), like below( these two images are selected from epoch33/40):
![image](https://user-images.githubusercontent.com/12395126/145926126-25a7cd75-e1b9-416c-b1dc-71e6cee7c128.png)
and
![image](https://user-images.githubusercontent.com/12395126/145926186-4d1d5082-0f17-4cbc-98d1-db54eec71b22.png)
 Do you know how to avoid this situation? Thanks in advance.

PS:
my dataset is a food image set and there are 150,000 images.
And i use this command to train my model 
`CUDA_VISIBLE_DEVICES=0,1,2,3 python bin/train.py -cn lama-fourier location=food data.batch_size=10 data.num_workers=8 trainer.kwargs.gpus=[0,1,2,3] trainer.kwargs.limit_train_batches=12360 optimizers.generator.lr=0.001 optimizers.discriminator.lr=0.0001`

**Comment by windj007** [comment]
Hi! Sorry for the late reply!

Did you resolved the issue?

What are the training and testing resolutions?

**Comment by windj007** [comment]
Do these artifacts appear on training images as well?

**Comment by liangzimei** [comment]
Yes, here is some training samples in last epoch.
![A20220120111002](https://user-images.githubusercontent.com/12395126/150265607-3493f9cb-c68d-4939-8272-175757c2d397.jpg)

**Comment by liangzimei** [comment]
> Do these artifacts appear on training images as well?

Hi, do you have any suggestions? Thanks.

**Comment by windj007** [comment]
Honestly, I did not have time to think about your issue thoroughly.

A couple of questions:
1. Could you please show training metrics from tensorboard? Especially discriminator scores and R1 gradient penalty, but others should be informative as well.
2. Did you try changing coefficient for R1 gradient penalty?

**Comment by abhishek7467** [comment]
**my cmd is  (EnvPython3_8) PS E:\Image_Inpainting\ImageWebApp\ImageApp> python3.8 train.py  location=E:\\Image_Inpainting\\ImageWebApp\\ImageApp\\my_dataset\\  data.batch_size=10 run_title="Image Inpainting"**


i am getting error like

**_hydra.errors.MissingConfigException: Cannot find primary config 'tiny_test.yaml'. Check that it's in your config search path.

Config search path:
        provider=hydra, path=pkg://hydra.conf
        provider=main, path=file://E:\Image_Inpainting\ImageWebApp\ImageApp\configs\training
        provider=schema, path=structured://_**
        
        
       could you please tell me where i am wrong and i have not tiny_test.yaml file
