### ISSUE TITLE
An automated implementation of lama: auto-lama

### ISSUE THREAD

**Issue by andy971022** [saic-mdal/lama#69]
Hi, thank you so much for making Lama happen. I'd like to share an app/implementation of using DE:TR, an object detection model, and Lama together.

https://github.com/andy971022/auto-lama 

Here are some demos that are pretty much self-explanatory.
![cat](https://user-images.githubusercontent.com/42510606/146686064-80dc70da-4b20-45e8-84ac-7ebd1e43cbfa.gif)
![park](https://user-images.githubusercontent.com/42510606/146686067-b762d541-6bbe-45e0-b315-952a2f4632b2.gif)
![buildings](https://user-images.githubusercontent.com/42510606/146686071-cded8801-103a-4d8f-8dee-f49788348daa.gif)

**Comment by windj007** [comment]
Hi! Sorry for the late reply and thank you very much for the contribution! I've added the reference to your github to our Readme
