### ISSUE TITLE
[Bug] In `predict.py`. images are not unpadded

### ISSUE THREAD

**Issue by ternaus** [saic-mdal/lama#73]
For inference, images are padded to be divisible by 8, but after the prediction is done they are not unpadded.

=> when one uses `bin/predict.py` input images and output images have a different shape

**Comment by cohimame** [comment]
Hello!

Vladimir, thank you for your bug report!

Gonna fix it in couple of days

**Comment by Jeff-Zilence** [comment]
Thank you for your nice code. I got similar issue. Has this been addressed in the current version?
<img width="675" alt="image" src="https://user-images.githubusercontent.com/46680018/152891400-5842ae1d-6131-43fd-bf48-5c15c0f0c663.png">

**Comment by Jeff-Zilence** [comment]
Thank you for your nice code. I got similar issue. Has this been addressed in current version?

**Comment by windj007** [comment]
Hi! Sorry for the late reply! No, have not fix this issue yet. The fix is pretty simple. If this is urgent for you, feel free to make a PR.

**Comment by hjq133** [comment]
nice code ! But problem still exist...

**Comment by ZeeRizvee** [comment]
Hi there. I also noticed the same and was looking for a fix. Can you please guide? @windj007

**Comment by ZeeRizvee** [comment]
Working perfectly now! @ternaus guess we can close the issue now
