### ISSUE TITLE
ade20k-resnet50dilated-ppm_deepsup/encoder_epoch_20.pth

### ISSUE THREAD

**Issue by llmir** [saic-mdal/lama#75]
It seems that the website storing the model is down. May I ask you to upload your backup model? Thank you very much.

http://sceneparsing.csail.mit.edu/model/pytorch/ade20k-resnet50dilated-ppm_deepsup/encoder_epoch_20.pth

![image](https://user-images.githubusercontent.com/16363216/147575182-37ee0546-bc2b-471f-8a6f-66c2cf3d6de1.png)

**Comment by senya-ashukha** [comment]
Hi @llmir, 

Try this one https://disk.yandex.ru/d/eMdArvFoJte6rQ

**Comment by llmir** [comment]
你好，邮件没有发错，这是林立的邮箱。紧急事情请发短信或者打电话到15521000952提醒我查看邮箱，谢谢！

**Comment by llmir** [comment]
Thx a lot!!

**Comment by llmir** [comment]
Sorry for bothering again, the following two models are also needed or I will come across this error when running the train code. Thx again!
error: https://github.com/CSAILVision/semantic-segmentation-pytorch/issues/110
models needed:  http://sceneparsing.csail.mit.edu/model/pretrained_resnet/mobilenet_v2.pth.tar     and      http://sceneparsing.csail.mit.edu/model/pretrained_resnet/resnet50-imagenet.pth

**Comment by llmir** [comment]
![image](https://user-images.githubusercontent.com/16363216/147578310-b5698ad6-26ca-42c3-88bc-6996f033e2b4.png)

**Comment by MSDuran** [comment]
Hello @senya-ashukha,
Could you also share ade20k-resnet50dilated-ppm_deepsup/decoder_epoch_20.pth?
