### ISSUE TITLE
Where to download the model for perceptual loss

### ISSUE THREAD

**Issue by gexahedron** [saic-mdal/lama#76]
Hi! The website http://sceneparsing.csail.mit.edu/model/pytorch/ade20k-resnet50dilated-ppm_deepsup/encoder_epoch_20.pth seems unavailable right now. Do you know, maybe, whether it's possible to download it from any other place?

**Comment by cohimame** [comment]
@senya-ashukha

**Comment by MSDuran** [comment]
I know this isn't the right place ,but I need this file ade20k-resnet50dilated-ppm_deepsup/decoder_epoch_20.pth.Could you share if you have?

**Comment by FrozenTear7** [comment]
https://github.com/CSAILVision/semantic-segmentation-pytorch/issues/273#issuecomment-1003503059
Linked solution worked for me.
![image](https://user-images.githubusercontent.com/31183971/147859710-840c4e2b-934d-4cd6-ae84-f76822b9c54b.png)

**Comment by senya-ashukha** [comment]
Hi, sorry for being slow, links are working now, I've backed them up, just in case;
