### ISSUE TITLE
What is LearnableSpatialTransformWrapper layer?

### ISSUE THREAD

**Issue by phongnhhn92** [saic-mdal/lama#79]
Hello guys,

Thanks for the code and project ! I am trying to understand your model and I found that you are using this layer after the FFC Resblock ? Can you explain what are you trying to do with this layer ? I can not find any details in the paper.

https://github.com/saic-mdal/lama/blob/0449ee2ced46f13539b16c5fe8103eb46f56c16d/saicinpainting/training/modules/spatial_transform.py#L7

**Comment by cohimame** [comment]
Hello!

Thank you!

We actually don't use this module, it's a leftover from old abandoned experiments.
