### ISSUE TITLE
Environment variable 'USER' not found

### ISSUE THREAD

**Issue by xinguo2** [saic-mdal/lama#80]
Thanks for your share! When I run python bin/train.py -cn lama-fourier location=my_dataset data.batch_size=10，the errors occured:
omegaconf.errors.InterpolationResolutionError: ValidationError raised while resolving interpolation: Environment variable 'USER' not found
    full_key: hydra.run.dir
    object_type=dict

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bin/train.py", line 74, in <module>
    main()
  File "/root/lama-main/saicinpainting/utils.py", line 163, in new_main
    main_func(*args, **kwargs)
  File "/root/.local/lib/python3.7/site-packages/hydra/main.py", line 53, in decorated_main
    config_name=config_name,
  File "/root/.local/lib/python3.7/site-packages/hydra/_internal/utils.py", line 368, in _run_hydra
    lambda: hydra.run(
  File "/root/.local/lib/python3.7/site-packages/hydra/_internal/utils.py", line 270, in run_and_report
    cur.tb_lasti = iter_tb.tb_lasti
AttributeError: 'NoneType' object has no attribute 'tb_lasti'

Could you tell me how to solve it, thanks!

**Comment by vonchenplus** [comment]
You just need to export USER environment variable.

**Comment by senya-ashukha** [comment]
Hi @xinguo2, yep recommendation by @vonchenplus is valid;

**Comment by hanp0** [comment]
> You just need to export USER environment variable.

Would you mind explaining how to do this?

**Comment by windj007** [comment]
just `export USER=$(whoami) ; ./train.py ...`

**Comment by micklexqg** [comment]
> just `export USER=$(whoami) ; ./train.py ...`

similar problem, is it needed to  export USER=$(whoami)  for windows? if needed, how to export it?

**Comment by micklexqg** [comment]
> export USER environment variable.

how to export? i do not know what is the USER environment variable.

**Comment by micklexqg** [comment]
I run  export TORCH_HOME=$(pwd) && export PYTHONPATH=$(pwd)
but still the same error.

**Comment by micklexqg** [comment]
@windj007 
Hi, thanks for your nice work,
![image](https://user-images.githubusercontent.com/13776012/209433825-e811ad57-2cd8-4194-bff8-d24b27c1eadf.png)
 the command of export TORCH_HOME=$(pwd) && export PYTHONPATH=$(pwd) seems not work...
so what should i do?
