### ISSUE TITLE
Start training from a pretrained model

### ISSUE THREAD

**Issue by Monalissaa** [saic-mdal/lama#81]
I can't load the trained checkpoint, how can I modify the code to load it?

**Comment by Monalissaa** [comment]
I found out how to load checkpoints, but the pre-trained model given by the author does not have the parameters of the discriminator. Can the author also release the parameters of the trained discriminator? 👀

**Comment by windj007** [comment]
In order to continue training, you have to add `+trainer.kwargs.resume_from_checkpoint=path_to_model.ckpt` to arguments of `train.py`.

Regarding full checkpoints - I think yes, we can do that

**Comment by vince2003** [comment]
can you release full checkpoints?

**Comment by Monalissaa** [comment]
> In order to continue training, you have to add `+trainer.kwargs.resume_from_checkpoint=path_to_model.ckpt` to arguments of `train.py`.
> 
> Regarding full checkpoints - I think yes, we can do that

Thanks again!

**Comment by windj007** [comment]
Full checkpoints released - please refer to #96
