### ISSUE TITLE
Colab error

### ISSUE THREAD

**Issue by Oltrex** [saic-mdal/lama#82]
FileNotFoundError: [Errno 2] No such file or directory: '/content/output/1224276_original_mask.png'

![sdxfcgvbhyunjiasddas](https://user-images.githubusercontent.com/70460251/149237969-c8a7f43b-5951-4937-ae37-fc837a0a128d.PNG)

It happens with both custom images and the ones as examples

**Comment by bbboy1901** [comment]
I got the same error message on Colab. The first error in the traceback indicates there's a problem with importing cv2. I was able to solve the problem with some help from this thread on Stackoverflow...

https://stackoverflow.com/questions/70537488/cannot-import-name-registermattype-from-cv2-cv2

Basically just uninstalling Colab's default opencv installation (v4.5.5.62) and installing a previous version (v4.1.2.30) fixed it.

I added these two lines to my Colab right after the main code installation cell to make it work:

!pip uninstall opencv-python-headless==4.5.5.62 --yes

!pip install opencv-python-headless==4.1.2.30

**Comment by Oltrex** [comment]
that fixed it¡ thanks, alse is there any way to make it output hd results, it heavily downscales it

**Comment by senya-ashukha** [comment]
Hi @bbboy1901,

Thx for the fix! It is now in the ipython notebook;

**Comment by senya-ashukha** [comment]
@Oltrex did you try to look at the output folder?

**Comment by senya-ashukha** [comment]
The initial issue is fixed, so I close this;

**Comment by Oltrex** [comment]
> Hi @Oltrex, did you try to look at the output folder?

yes, it was in there,  im new to colab and these stuff so i didnt knew i could just browse files and download it, thanks for the help everyone

**Comment by siam009** [comment]
Still facing the same error
