### ISSUE TITLE
Integrate to iOS

### ISSUE THREAD

**Issue by siam009** [saic-mdal/lama#87]
I am trying to integrate this in a ios project. But I couldn't find any way to integrate this. Can anyone help me with this.

**Comment by windj007** [comment]
Hi! We cannot help you with anything related to production. However, I'd suggest to search for manuals on "pytorch coreml conversion"

**Comment by mgstar1021** [comment]
Hello @siam009, Did you solved your problem? Is it possible to convert mlmodel?

**Comment by siam009** [comment]
No. I couldn't solve that problem.

**Comment by siam009** [comment]
someone solved that. To them who wants to integrate into ios please have a look: [](https://github.com/advimman/lama/issues/250)
