### ISSUE TITLE
Releasing the Pretrained Full Checkpoints

### ISSUE THREAD

**Issue by yzhouas** [saic-mdal/lama#89]
Could the authors release the full checkpoints including the discriminator?
I would like to finetune the model.

Thanks so much.

**Comment by windj007** [comment]
We have been planing to do it for pretty long time. I hope we'll find the time soon.

**Comment by yzhouas** [comment]
Thanks so much and I am really looking forward to it!

**Comment by windj007** [comment]
Hi! I've just uploaded full checkpoint for big-lama  https://disk.yandex.ru/d/wJ2Ee0f1HvasDQ

**Comment by affromero** [comment]
Hello, there is a folder in https://disk.yandex.ru/d/wJ2Ee0f1HvasDQ/lama-celeba-hq/lama-fourier-with-discr, is it possible that you forgot to add that model? Or lama-fourier-with-discr for Places?

**Comment by windj007** [comment]
Yes, I forgot to add this model. Are you still interested in it?

**Comment by DQiaole** [comment]
> Hi! I've just uploaded full checkpoint for big-lama https://disk.yandex.ru/d/wJ2Ee0f1HvasDQ - see `big-lama-with-discr` subfolder
> 
> Please share your experience with fine-tuning - whether it helps and how much

Hi! I find it's difficult for me to fine-tune the model without the optimizer's parameter. 
Could you also share the optimizer?
Thanks so much.

**Comment by bshelkhonov** [comment]
> Yes, I forgot to add this model. Are you still interested in it?

Hello. I'm working on my graduation work and would very appreciate it if you release weights for lama fourier with discr for Places.

**Comment by asrays** [comment]
@windj007 can you please share the weight file and config for lama-fourier-with-discr. I just need to inference with this model.
