### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/data/checkpoint/config.yaml'

### ISSUE THREAD

**Issue by dave0824** [saic-mdal/lama#91]
Execute the command：bash docker/2_predict.sh /usr/local/docker/big-lama /usr/local/docker/LaMa_test_images /usr/local/docker/output device=cpu
There is an error：FileNotFoundError: [Errno 2] No such file or directory: '/data/checkpoint/config.yaml'
I don't know where this file comes from, could you please answer it? Thank you！

**Comment by windj007** [comment]
Could you please show the output of `ls  /usr/local/docker/big-lama`?

**Comment by windj007** [comment]
This script maps files on your filesystem to virtual volumes within docker and then spawns a docker container - so `'/data/checkpoint/config.yaml'` is a path within container. `/data/checkpoint` is supposed to point to the actual folder you specify as the first argument of `2_predict` - `/usr/local/docker/big-lama` in your case.

The correct value for this argument would be a path to a folder which contains `config.yaml` and `models/best.ckpt` files (which together constitute the checkpoint in our pipeline)

**Comment by windj007** [comment]
I'm closing the issue for now. If you have any other questions, feel free to reopen it or create a new one.
