### ISSUE TITLE
Image2Image model

### ISSUE THREAD

**Issue by armheb** [saic-mdal/lama#93]
Congrats on your great work and thanks for sharing your code. I'm using this model for an image2image translation. but after training for some time I'm losing the details from the input image in the predicted results. do you have any suggestions on how to modify the loss functions for better detail perservation? Thanks.

**Comment by windj007** [comment]
Hi! Sorry for the late reply.

> do you have any suggestions on how to modify the loss functions for better detail perservation?

The answer would depend very much on the task and the dataset. Given more details, I can probably recommend something.

**Comment by armheb** [comment]
Thanks for your reply. Basically, I'm using the lama to get rid of some artifacts in my images. Below is an example image
![batch0000107](https://user-images.githubusercontent.com/18460769/156889656-0f5573c2-3b2b-4f27-ac75-ecd5a208a4cb.jpg)
.
from left to right is the input image, target, and lama output. as seen above I'm losing some of the details in the texture and images on the shirt. I was hoping to modify the loss functions to better preserve these features in the input image. Thanks.

**Comment by windj007** [comment]
I see.. I think that this task is pretty different from what Lama was deisgned for - so you probably need to change not only losses, but also architecture and data generation process. There are plenty of possible options to try from stochasticity in generator to custom perceptual losses.

Also, it seems that FFC is a bit meaningless in that task - in inpainting it increases receptive field and helps to capture patterns - but in this example mostly local information is relevant.

**Comment by armheb** [comment]
Thanks, Yes I have changed the data generation process and architecture. I'll also try custom perceptual losses too. Thank you.
