### ISSUE TITLE
Question about big-lama.yaml

### ISSUE THREAD

**Issue by jxbs** [saic-mdal/lama#98]
Hi, thanks for your excellent works.
I have a question about what is "weights_path: ${env:TORCH_HOME}" mean in big-lama.yaml ? When I retrain the works, I don't kown what I had writen in here.
Thank you for time!

**Comment by micklexqg** [comment]
> Hi, thanks for your excellent works. I have a question about what is "weights_path: ${env:TORCH_HOME}" mean in big-lama.yaml ? When I retrain the works, I don't kown what I had writen in here. Thank you for time!

have you solved it? I came across a similar problem, how to export ${env:TORCH_HOME} for windows?

**Comment by windj007** [comment]
I do not know what is the default value for `TORCH_HOME` in Windows (for linux it's like `<user home dir>/.torch`). Just [set](https://superuser.com/questions/212150/how-to-set-env-variable-in-windows-cmd-line) TORCH_HOME to any path you'd like the models to be stored. If you want to use SegmPL, then download and unpack Ade20k network to that folder.
