### ISSUE TITLE
please add our cleaner app on README

### ISSUE THREAD

**Issue by kjsik11** [saic-mdal/lama#99]
[https://www.hama.app/en](https://www.hama.app/en) - A fast web application that lets you erase objects from your photo with a single brush by https://github.com/coxwave

**Comment by windj007** [comment]
Hi! Thank you for the links! Hama looks great!

I wonder, if your app has an interactive segmentation technology, which refines contours of the object to be deleted?

Also, if it's possible, could you please also add a link to our repo somewhere to your app (e.g. as a last item to the FAQ)?

**Comment by kjsik11** [comment]
Hi Roman.

Thank you for the reply.
We are actually trying to implement a panoptic segmentation model in our application so that user doesn’t have to brush every object.
We’ll probably let the user click on the object and it will automatically be brushed.
And as you said, we can refine the contours of the objects.
Also, we’ll add a link to this repo in the FAQ in the next update!

Thank you :slightly_smiling_face:

**Comment by kjsik11** [comment]
Hi Roman.

We just updated our website and added a link to this repo in our FAQ. Please check it out :)
If you need anything else, feel free to reach out to us.
Email: [admin@coxwave.com](mailto:admin@coxwave.com)

Thank you again for building this awesome AI ❤️

**Comment by zhenzi0322** [comment]
Hi, how many iterations did you train to generate the model for this application?

**Comment by zhenzi0322** [comment]
> Hi Roman.
> 
> We just updated our website and added a link to this repo in our FAQ. Please check it out :) If you need anything else, feel free to reach out to us. Email: [admin@coxwave.com](mailto:admin@coxwave.com)
> 
> Thank you again for building this awesome AI ❤️

Hi, how many iterations did you train to generate the model for this application?

**Comment by windj007** [comment]
@kjsik11 I've added a link to Hama to our readme! Thank you! Is my description of Hama fair?

**Comment by roimulia2** [comment]
Hey @kjsik11, can I ask where did you host your model at? We tried the different solutions but every one we tried was super expensive :/
